---
# tasks file for k8s-node
## Here starts K8S installing
- name: install "apt-transport-https curl" "Debian"
  when: ansible_os_family == "Debian"
  apt: 
   name: ['apt-transport-https','curl']
   state: present
   update_cache: yes
  environment: 
    http_proxy: "{{proxy_http}}"
    https_proxy: "{{proxy_https}}"

- name: curl for package "Debian"
  when: ansible_os_family == "Debian"
  #shell: "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  environment: 
    http_proxy: "{{proxy_http}}"
    https_proxy: "{{proxy_https}}"

- name: add package source to package-list "Debian"
  when: ansible_os_family == "Debian"
  template:
    src: "kubernetes.list.j2"
    dest: "/etc/apt/sources.list.d/kubernetes.list"

- name: install "kubelet, kubeadm, kubectl" "Debian"
  when: ansible_os_family == "Debian"
  apt:
   name: ['kubelet','kubeadm','kubectl','bash-completion']
   state: present
   update_cache: yes
  environment:
   http_proxy: "{{proxy_http}}"
   https_proxy: "{{proxy_https}}"

- name: add repository "RedHat"
  when: ansible_os_family == "RedHat"
  template:
    src: "kubernetes.repo.j2"
    dest: "/etc/yum.repos.d/kubernetes.repo"
  environment:
    http_proxy: "{{proxy_http}}"
    https_proxy: "{{proxy_https}}"

- name: Dirty Hack "RedHat"
  when: ansible_os_family == "RedHat"
  shell: 
   cmd: echo -e "y" | yum repolist
  environment:
    http_proxy: "{{proxy_http}}"
    https_proxy: "{{proxy_https}}"   

- name: install "kubeadm, kubelet, kubectl" "RedHat"
  when: ansible_os_family == "RedHat"
  yum: 
    name: ['kubelet','kubeadm','kubectl','bash-completion']
    state: present
    update_cache: yes
  environment:
    http_proxy: "{{proxy_http}}"
    https_proxy: "{{proxy_https}}"

- name: configure required binary
  become: yes
  sysctl:
   name: net.bridge.bridge-nf-call-iptables
   value: '1'
   sysctl_set: yes
   state: present
   reload: yes

- name: Enable and start kubelet
  service:
    name: kubelet
    enabled: yes
    state: restarted